###
POST http://localhost:8080/api/registration/user
Content-Type: application/json

{
  "firstName": "Sankalp",
  "lastName": "Thorat",
  "dob": "2002-02-02",
  "reference": "CAMPUS_PLACEMENT",
  "emailId": "sankalpt0202@gmail.com",
  "cardType": "PAN CARD",
  "cardNumber": "ABCDE1234F",
  "mobileNo": "9876543210",
  "positionApplied": "SOFTWARE_DEVELOPER",
  "qualification": "BTECH",
  "specialization": "COMPUTERSCIENCE",
  "collegeName": "IIIT KURNOOL",
  "roleId": 1
}

###
POST http://localhost:8080/api/registration/user
Content-Type: application/json

{
  "firstName": "RAHUL",
  "lastName": "SHARMA",
  "dob": "1998-05-15",
  "reference": "LINKEDIN",
  "emailId": "rahul.sharma.dev@example.com",
  "cardType": "PAN CARD",
  "cardNumber": "CQZPR9876M",
  "mobileNo": "9876500001",
  "positionApplied": "BACKEND ENGINEER",
  "qualification": "MTECH",
  "specialization": "SOFTWARE ENGINEERING",
  "collegeName": "IIT BOMBAY",
  "roleId": 2
}