spring.datasource.url=jdbc:oracle:thin:@10.10.10.234:1521/pdb.concerto.in
spring.datasource.username=DEV_E_LEARNING
spring.datasource.password=orcl1234
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true